# Generated by Django 2.2.10 on 2020-12-31 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='название')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата старта')),
                ('end_date', models.DateTimeField(verbose_name='дата окончания')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name_plural': 'опросы',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст вопроса')),
                ('question_type', models.CharField(choices=[('one option', 'one option'), ('text response', 'text response'), ('multiple options', 'multiple options')], default='text response', max_length=25)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='ответ')),
                ('user_id', models.IntegerField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.Poll')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.Question')),
            ],
            options={
                'verbose_name_plural': 'ответы',
                'ordering': ('question',),
            },
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('user_id', 'question'), name='unique_answer'),
        ),
    ]
